name: nyari apa bre?!
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositori
        uses: actions/checkout@v3
      - name: Update file
        run: |
          echo "Auto update pada $(date)" >> green.txt
          git config --global user.name "AutoBot"
          git config --global user.email "bot@example.com"
          git add green.txt
          git commit -m "ngapain sampe sini? $(date)"
          git push
