name: Auto Commit Green
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Auto update pada $(date)" >> green.txt
          git config --global user.name "AutoBot"
          git config --global user.email "bot@example.com"
          git add green.txt
          git commit -m "Bikin hijau pada $(date)"
          git push
